### ISSUE TITLE
QQ-kirito 微软账户无法登陆

### ISSUE THREAD

**Issue by YangSpring114** [Blessing-Studio/WonderLab.Override#11]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

如标题

### 日志

非常抱歉您的 WonderLab 又又又炸了，以下是此次崩溃的错误信息
----------------------------------------------------------------------
系统平台：Windows
异常名：System.NullReferenceException
----------------------------------------------------------------------
异常堆栈信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at MinecraftLaunch.Modules.Authenticator.MicrosoftAuthenticator.AuthAsync(Action`1 func) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab.Core/Modules/Authenticator/MicrosoftAuthenticator.cs:line 206
   at wonderlab.ViewModels.Pages.DialogPageViewModel.MicrosoftSelectedAction() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/ViewModels/Pages/DialogPageViewModel.cs:line 78
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 276
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at wonderlab.Program.Main(String[] args) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/Program.cs:line 22

### 问题复现率

必现

### 复现步骤

登陆即可复现

### 操作系统版本

全平台

### WonderLab版本

1.2.5-preview

**Comment by YangSpring114** [comment]
已修复
