### ISSUE TITLE
在Arch Linux上无法启动程序

### ISSUE THREAD

**Issue by MCSeekeri** [Blessing-Studio/WonderLab.Override#13]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

自行编译或下载最新Release运行都无法启动程序。
即使从AUR内安装了MiSans字体。

### 日志

```
{"errorType":"System.InvalidOperationException","errorInfo":"非常抱歉您的 WonderLab 又又又炸了，以下是此次崩溃的错误信息
----------------------------------------------------------------------
系统平台：Linux
异常名：System.InvalidOperationException
----------------------------------------------------------------------
异常堆栈信息：System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Base/Media/FontManager.cs:line 33
   at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Base/Media/FontManager.cs:line 53
   at Avalonia.Media.Typeface.get_GlyphTypeface() in /_/src/Avalonia.Base/Media/Typeface.cs:line 84
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget..ctor(ServerCompositor compositor, Func`1 renderTargetFactory) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs:line 28
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 renderTargetFactory) in /_/src/Avalonia.Base/Rendering/Composition/Compositor.Factories.cs:line 17
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor) in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 47
   at Avalonia.X11.X11Window.CreateRenderer(IRenderRoot root) in /_/src/Avalonia.X11/X11Window.cs:line 394
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/TopLevel.cs:line 147
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/WindowBase.cs:line 61
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl) in /_/src/Avalonia.Controls/WindowBase.cs:line 57
   at Avalonia.Controls.Window..ctor(IWindowImpl impl) in /_/src/Avalonia.Controls/Window.cs:line 230
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 221
   at wonderlab.Views.Windows.MainWindow..ctor() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/Views/Windows/MainWindow.axaml.cs:line 32
   at wonderlab.App.OnFrameworkInitializationCompleted() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/App.axaml.cs:line 31
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 289
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 148
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at wonderlab.Program.Main(String[] args) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/Program.cs:line 28"}
```

### 问题复现率

必现

### 复现步骤

1.下载最新的Release
2.运行

### 操作系统版本

Linux

### WonderLab版本

cf1e75a68286e2ebf7a3abeb9284d8a77c124547

### 补充信息

操作系统为 Arch Linux + KDE Plasma + Wayland

**Comment by FTS427** [comment]
写一个“start.sh”，如下：
`#! sh
export LC_CTYPE=en_US.UTF-8 && ./wonderlab`

**Comment by FTS427** [comment]
> 

还有，这个问题可是有的，当时花了好长时间解决
参见 #3 （已解决）

**Comment by JWJUN233233** [comment]
详见文件desktop写法 抄exec
