### ISSUE TITLE
如果导入非整合包的压缩文件程序会闪退

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#30]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

如果在导入整合包时选择了一个非整合包的文件WonderLab就会先卡死，之后自己闪退

### 日志

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at wonderlab.Class.Utils.ModpacksUtils.CurseforgeModpacksInstallAsync(String path) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/Class/Utils/ModpacksUtils.cs:line 113
at wonderlab.Class.Utils.ModpacksUtils.ModpacksInstallAsync(String path) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/Class/Utils/ModpacksUtils.cs:line 48
at wonderlab.ViewModels.Pages.HomePageViewModel.ImportModpacksAction() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/ViewModels/Pages/HomePageViewModel.cs:line 341
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
at Avalonia.Threading.DispatcherOperation.Execute()
at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
at Avalonia.Threading.Dispatcher.Signaled()
at Avalonia.X11.X11PlatformThreading.CheckSignaled()
at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
at wonderlab.Program.Main(String[] args) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/Program.cs:line 16

这是shell输出的

### 问题复现率

必现

### 复现步骤

1. 打开WonderLab，在主界面打开“当前核心”
2. 选择“导入现有整合包”，选择一个非整合包的文件
3. 问题出现，程序闪退

### 操作系统版本

Linux

### WonderLab版本

1.2.6-preview

**Comment by JWJUN233233** [comment]
又没加try。。。
