### ISSUE TITLE
QQ-ic58n 下载出现null问题

### ISSUE THREAD

**Issue by JWJUN233233** [Blessing-Studio/WonderLab.Override#6]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

下载1.20时出现

### 日志

非常抱歉您的 WonderLab 又又又炸了，以下是此次崩溃的错误信息
----------------------------------------------------------------------
系统平台：MacOS
异常名：System.NullReferenceException
----------------------------------------------------------------------
异常堆栈信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at MinecraftLaunch.Modules.Installer.ResourceInstaller.GetAssetResourcesAsync() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab.Core/Modules/Installer/ResourceInstaller.cs:line 110
   at MinecraftLaunch.Modules.Installer.ResourceInstaller.DownloadAsync(Action`2 func) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab.Core/Modules/Installer/ResourceInstaller.cs:line 35
   at wonderlab.ViewModels.Pages.HomePageViewModel.<>c__DisplayClass41_0.<<LaunchTaskAction>b__13>d.MoveNext() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/ViewModels/Pages/HomePageViewModel.cs:line 249
--- End of stack trace from previous location ---
   at wonderlab.ViewModels.Pages.HomePageViewModel.<>c__DisplayClass41_0.<<LaunchTaskAction>g__ResourceCheckOutAsync|3>d.MoveNext() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/ViewModels/Pages/HomePageViewModel.cs:line 247
--- End of stack trace from previous location ---
   at wonderlab.ViewModels.Pages.HomePageViewModel.LaunchTaskAction() in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/ViewModels/Pages/HomePageViewModel.cs:line 147
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4586
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at wonderlab.Program.Main(String[] args) in /home/runner/work/WonderLab.Override/WonderLab.Override/wonderlab/Program.cs:line 22

### 问题复现率

必现

### 复现步骤

1.下载1.20

### 操作系统版本

全平台

### WonderLab版本

1.2.5-preview

**Comment by JWJUN233233** [comment]
![IMG_0855](https://github.com/Blessing-Studio/WonderLab.Override/assets/66861021/3ba71300-ef22-447b-885a-6a8cda3ebecc)
